const state = { stars:Number(localStorage.getItem('mathMissionStars')||0), streak:0, exercise:null, mode:null, question:null };
const rewards=[{at:5,name:'Badge Explorateur',icon:'🧭'},{at:15,name:'Badge Éclair',icon:'⚡'},{at:30,name:'Badge Pizza des fractions',icon:'🍕'},{at:50,name:'Super calculateur',icon:'🏆'}];
const $=id=>document.getElementById(id);
function updateProgress(){ $('starCount').textContent=state.stars; const next=rewards.find(r=>r.at>state.stars); $('badges').innerHTML=rewards.map(r=>`<div class="badge ${state.stars>=r.at?'unlocked':''}" aria-label="${r.name}">${r.icon}</div>`).join(''); if(next){const prev=[...rewards].reverse().find(r=>r.at<=state.stars)?.at||0;$('rewardName').textContent=next.name;$('rewardIcon').textContent=next.icon;$('rewardProgress').textContent=`Encore ${next.at-state.stars} étoile${next.at-state.stars>1?'s':''} !`;$('rewardBar').style.width=`${(state.stars-prev)/(next.at-prev)*100}%`;}else{$('rewardName').textContent='Collection complète !';$('rewardProgress').textContent='Tu as tous les badges !';$('rewardIcon').textContent='🌟';$('rewardBar').style.width='100%';}}
function home(){ $('homeView').classList.remove('hidden');$('gameView').classList.add('hidden');state.streak=0; }
function renderMissions(){ $('missionGrid').innerHTML=Object.entries(EXERCISES).map(([id,x])=>`<button class="mission" type="button" data-mission="${id}" style="background:${x.color};--card-shadow:${x.shadow}"><span class="icon">${x.icon}</span><h3>${x.title}</h3><p>${x.description}</p><div class="chips">${x.modes.map(m=>`<span class="chip">${m.label}</span>`).join('')}</div></button>`).join(''); document.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mission)));}
function start(id){state.exercise=EXERCISES[id];state.mode=state.exercise.modes[0].id;$('homeView').classList.add('hidden');$('gameView').classList.remove('hidden');$('gameTitle').textContent=state.exercise.title;$('gameKicker').textContent='Nouvelle mission';$('modeSwitch').innerHTML=state.exercise.modes.map((m,i)=>`<button type="button" class="${i===0?'active':''}" data-mode="${m.id}">${m.label}</button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));newQuestion();}));newQuestion();}
function newQuestion(){state.question=state.exercise.next(state.mode);const q=state.question;$('question').innerHTML=q.question;$('questionLabel').textContent=q.label;$('hint').textContent=q.hint||'';$('feedback').textContent='';$('streak').textContent=`🔥 Série : ${state.streak}`; renderAnswer(q);}
function renderAnswer(q){const form=$('answerForm'); if(q.type==='qcm'||q.type==='compare'){form.innerHTML=`<div class="choices">${q.options.map(x=>`<button class="choice" type="button" data-answer="${x}">${x}</button>`).join('')}</div>`;form.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(b.dataset.answer));return;} if(q.type==='factors'){form.innerHTML=`<div class="factor-inputs"><input class="number-input" inputmode="numeric" aria-label="Premier facteur"><b>×</b><input class="number-input" inputmode="numeric" aria-label="Deuxième facteur"></div><button class="submit" type="submit">Je valide</button>`;}else if(q.type==='pizza'){form.innerHTML=`<div class="pizza-wrap">${Array.from({length:q.denominator},(_,i)=>`<button class="pizza-piece" type="button" aria-label="Part ${i+1}" aria-pressed="false"></button>`).join('')}</div><button class="submit" type="submit">Je valide</button>`;form.querySelectorAll('.pizza-piece').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');b.setAttribute('aria-pressed',b.classList.contains('selected'));});}else{form.innerHTML=`<input class="number-input" inputmode="numeric" aria-label="Ta réponse" autofocus><button class="submit" type="submit">Je valide</button>`;}form.onsubmit=e=>{e.preventDefault();let answer;if(q.type==='factors'){answer=[...form.querySelectorAll('input')].map(x=>Number(x.value)).sort((a,b)=>a-b).join(',');}else if(q.type==='pizza'){answer=form.querySelectorAll('.pizza-piece.selected').length;}else answer=form.querySelector('input').value.trim();check(answer);};form.querySelector('input')?.focus();}
function check(answer){const q=state.question;const ok=Array.isArray(q.answer)?q.answer.includes(answer):String(answer)===String(q.answer);const feedback=$('feedback');if(ok){state.streak++;state.stars++;localStorage.setItem('mathMissionStars',state.stars);feedback.textContent='Bravo ! +1 étoile ⭐';feedback.className='feedback good';updateProgress();const r=rewards.find(r=>r.at===state.stars);if(r){$('celebrationText').textContent=`Tu as débloqué : ${r.name} ${r.icon}`;$('celebration').showModal();}setTimeout(newQuestion,950);}else{state.streak=0;feedback.textContent='Presque ! Essaie encore, tu peux y arriver.';feedback.className='feedback bad';$('streak').textContent='🔥 Série : 0';}}
$('backButton').onclick=home;$('closeDialog').onclick=()=>$('celebration').close();renderMissions();updateProgress();
